name: Build and push images

on:
  release:
    types: [ published ]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - uses: nowsprinting/check-version-format-action@v3
        id: version
        with:
          prefix: 'v'

      - name: Version tag only step
        run: |
          echo "Found valid version format in tag!"
          echo "Full version: ${{ steps.version.outputs.full }}"
          echo "Major version: ${{ steps.version.outputs.major }}"
          echo "Major with pre-release: ${{ steps.version.outputs.major_prerelease }}"

      - name: Exit if version format is invalid
        run: exit 1
        if: steps.version.outputs.is_valid != 'true'

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker image with release git tag
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ github.repository }}:${{ steps.version.outputs.full_without_prefix }}
            ${{ github.repository }}:latest
          platforms: |
            linux/amd64
            linux/arm64
